# Generated by Django 5.2.1 on 2025-05-26 01:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_entry_profile_delete_user_entry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='mood_score',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='entry',
            name='productivity_score',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='entry',
            name='stress_level',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='entry',
            name='work_hours',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='caffeine_intake',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='exercise',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sleep_quality',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.IntegerField(choices=[(1, 'Happy'), (2, 'Sad'), (3, 'Neutral')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dreams', to='api.profile')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream', to='api.entry')),
            ],
        ),
    ]
