# Generated by Django 5.2.1 on 2025-06-08 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_entry_mood_score_entry_productivity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='screen_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dream',
            name='entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dream', to='api.entry'),
        ),
    ]
