# Generated by Django 5.2.1 on 2025-10-23 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_entry_screen_time_alter_dream_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dream',
            name='entry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dream', to='api.entry'),
        ),
    ]
