# Generated by Django 5.2.1 on 2025-10-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_entry_notes_alter_dream_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
