# Generated by Django 5.2.1 on 2025-10-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_entry_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='caffeine_intake',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='exercise',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
